# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feVC0J6g7jEUGqYAFcgjYAFruTOwnTZh
"""

import streamlit as st
import pandas as pd
import numpy as np

st.title('Uber pickups in NYC')

DATE_COLUMN = 'date/time'
DATA_URL = ('https://s3-us-west-2.amazonaws.com/'
            'streamlit-demo-data/uber-raw-data-sep14.csv.gz')

@st.cache_data
def load_data(nrows):
  data = pd.read_csv(DATA_URL, nrows=nrows)
  lowercase = lambda x: str(x). lower ()
  data.rename (lowercase, axis='columns', inplace=True)
  data[DATE_COLUMN] = pd.to_datetime(data[DATE_COLUMN])
  return data

data_load_state = st.text('Loading data ... ')
data = load_data(10000)
data_load_state.text("Done! (using st. cache_data)")

if st.checkbox('Show raw data'):
  st.subheader('Raw data')
  st.write(data)

st.subheader('Number ot pickups by hour')
hist_values = np.histogram(data[DATE_COLUMN].dt.hour, bins=24, range=(0,24))[0]
st.bar_chart(hist_values)

# Añadir un selectbox para elegir el tipo de gráfico
chart_type = st.selectbox(
    "Selecciona el tipo de gráfico para mostrar las recogidas por hora",
    options=["Barras", "Líneas", "Área"]
)

# Mostrar el gráfico según la opción seleccionada
if chart_type == "Barras":
    st.bar_chart(hist_values)
elif chart_type == "Líneas":
    st.line_chart(hist_values)
elif chart_type == "Área":
    st.area_chart(hist_values)
# Somc number in the rangc 0 23
hour_to_filter = st.slider('hour', 0, 23, 17)
filtered_data = data[data[DATE_COLUMN].dt.hour == hour_to_filter]

st.subheader('Map of all pickups at %s:00' % hour_to_filter)
st.map(filtered_data)

